version : '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - ES_HEAP_SIZE=256m
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - /home/rancher/esdata:/usr/share/elasticsearch/data
    networks:
      - bot
  bot:    
    image: feira-bot:latest
    environment:
      - TELEGRAM_TOKEN=796249578:AAG3R0du-nJ5bCe-dW1wTLRH2dMyZdeZ4xg
    networks:
      - bot

networks:
  bot: