version : '2'
services:
  bot:    
    image: feira-bot:latest
    container_name: feira-bot
    hostname: feira-bot
    restart: always
    env_file:
      - .env
    networks:
      - elasticsearch

networks:
  elasticsearch:
    external: true
